apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: polcom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: homepage-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: homepage-icons
              mountPath: /usr/share/nginx/html/icons
      volumes:
        - name: homepage-html
          configMap:
            name: homepage-html
        - name: homepage-icons
          persistentVolumeClaim:
            claimName: nfs-dynamic-pvc
